server:
  port: 9010

spring:
  application:
    name: AuthService
  app:
    jwtSecret: mySecretKey123912738aopsgkjsebqndfsopkvajoirjgh91f2opfng2moknm
    jwtExpirationMs: 3000000
  datasource:
    url: jdbc:h2:file:./data/test-user-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true

logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
      hibernate:
        SQL: DEBUG
    com.nagarro.nagp: DEBUG