server:
  port: 9010
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  app:
    jwtSecret: mySecretKey123912738aopsgkjsebqndfsopkvajoirjgh91f2opfng2moknm
    jwtExpirationMs: 3000000
  datasource:
    url: jdbc:h2:file:./data/user-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
      hibernate:
        SQL: DEBUG
    com.nagarro.nagp: DEBUG