server:
  port: 0
  servlet:
    context-path: /leave

spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:h2:file:./data/leave-balance-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.nagarro.nagp: DEBUG

    org.springframework.web: DEBUG
#    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG

    org.springframework.security: DEBUG

    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE